#ifndef __psrfits2psrfits_cmd__
#define __psrfits2psrfits_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -b: The number of bits in each output sample (4 or 8) */
  char numbitsP;
  int numbits;
  int numbitsC;
  /***** -o: Base name of the output psrfits file */
  char outfileP;
  char* outfile;
  int outfileC;
  /***** -i: Invert the band */
  char invertP;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

extern void showOptionValues(void);

#endif

